<?php

declare(strict_types=1);

namespace Blockstudio\PHPStan\GitHooks;

use Blockstudio\PHPStan\Theme\CommandResult;
use Blockstudio\PHPStan\Theme\CommandRunner;

/**
 * Installs and removes the analysis-only hook selected by blockstudio.json.
 */
final class HookManager
{
    private const MARKER = '# Generated by Blockstudio. Do not edit.';
    private const STATE_VERSION = 1;

    public function __construct(
        private readonly CommandRunner $runner = new CommandRunner()
    ) {
    }

    public function sync(string $projectRoot, string $configurationPath): HookSyncResult
    {
        $projectRoot = $this->existingDirectory($projectRoot);
        $enabled = $this->isEnabled($configurationPath);

        return $enabled
            ? $this->enable($projectRoot)
            : $this->disable($projectRoot);
    }

    public function remove(string $projectRoot): HookSyncResult
    {
        return $this->disable($this->existingDirectory($projectRoot));
    }

    private function enable(string $projectRoot): HookSyncResult
    {
        $repositoryRoot = $this->repositoryRoot($projectRoot);
        $commonGitDirectory = $this->commonGitDirectory($repositoryRoot);
        $managedRoot = $commonGitDirectory . '/blockstudio';
        $managedHooksPath = $managedRoot . '/hooks';
        $managedHookPath = $managedHooksPath . '/pre-commit';
        $statePath = $managedRoot . '/hooks-state.json';
        $state = $this->readState($statePath);
        $currentHooksPath = $this->currentHooksPath($repositoryRoot);

        if (
            $this->samePath(
                $this->resolveHooksDirectory(
                    $currentHooksPath,
                    $repositoryRoot,
                    $commonGitDirectory
                ),
                $managedHooksPath
            )
            && $state === null
        ) {
            throw new \RuntimeException(
                'core.hooksPath points at Blockstudio, but its ownership state is missing. '
                . 'Restore core.hooksPath manually before syncing.'
            );
        }

        if (is_file($managedHookPath) && !$this->isOwnedFile($managedHookPath)) {
            throw new \RuntimeException(
                sprintf(
                    'Refusing to overwrite the user-owned hook at %s.',
                    $managedHookPath
                )
            );
        }

        $previousHooksPath = $state !== null
            ? $state['previousHooksPath']
            : $currentHooksPath;

        if (
            $state !== null
            && !$this->samePath(
                $this->resolveHooksDirectory(
                    $currentHooksPath,
                    $repositoryRoot,
                    $commonGitDirectory
                ),
                $managedHooksPath
            )
        ) {
            $previousHooksPath = $currentHooksPath;
        }

        $projectRelativePath = $this->relativePath(
            $repositoryRoot,
            $projectRoot
        );
        $hook = $this->hookContents(
            $projectRelativePath,
            $previousHooksPath,
            $repositoryRoot,
            $commonGitDirectory,
            $managedHookPath
        );

        $this->ensureDirectory($managedHooksPath);
        $this->writeFile($managedHookPath, $hook, 0755);
        $this->writeFile(
            $statePath,
            json_encode(
                [
                    'version' => self::STATE_VERSION,
                    'previousHooksPath' => $previousHooksPath,
                    'projectRelativePath' => $projectRelativePath,
                ],
                JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR
            ) . "\n",
            0644
        );
        $this->setHooksPath($repositoryRoot, $managedHooksPath);

        return new HookSyncResult('enabled', $managedHookPath);
    }

    private function disable(string $projectRoot): HookSyncResult
    {
        $repositoryRoot = $this->repositoryRoot($projectRoot);
        $commonGitDirectory = $this->commonGitDirectory($repositoryRoot);
        $managedRoot = $commonGitDirectory . '/blockstudio';
        $managedHooksPath = $managedRoot . '/hooks';
        $managedHookPath = $managedHooksPath . '/pre-commit';
        $statePath = $managedRoot . '/hooks-state.json';
        $state = $this->readState($statePath);
        $currentHooksPath = $this->currentHooksPath($repositoryRoot);
        $usesManagedPath = $this->samePath(
            $this->resolveHooksDirectory(
                $currentHooksPath,
                $repositoryRoot,
                $commonGitDirectory
            ),
            $managedHooksPath
        );

        if ($state === null) {
            if ($usesManagedPath || is_file($managedHookPath)) {
                throw new \RuntimeException(
                    'Blockstudio hook files or Git configuration exist without ownership state. '
                    . 'No files were changed.'
                );
            }

            return new HookSyncResult('disabled', $managedHookPath);
        }

        if (is_file($managedHookPath) && !$this->isOwnedFile($managedHookPath)) {
            throw new \RuntimeException(
                sprintf(
                    'Refusing to remove the user-owned hook at %s.',
                    $managedHookPath
                )
            );
        }

        if ($usesManagedPath) {
            $this->restoreHooksPath(
                $repositoryRoot,
                $state['previousHooksPath']
            );
        }

        if (is_file($managedHookPath) && !@unlink($managedHookPath)) {
            throw new \RuntimeException(
                sprintf('Unable to remove the managed hook at %s.', $managedHookPath)
            );
        }
        if (is_file($statePath) && !@unlink($statePath)) {
            throw new \RuntimeException(
                sprintf('Unable to remove the managed state at %s.', $statePath)
            );
        }

        $this->removeDirectoryIfEmpty($managedHooksPath);
        $this->removeDirectoryIfEmpty($managedRoot);

        return new HookSyncResult('disabled', $managedHookPath);
    }

    private function isEnabled(string $configurationPath): bool
    {
        if (!is_file($configurationPath)) {
            return false;
        }

        $contents = file_get_contents($configurationPath);
        if ($contents === false) {
            throw new \RuntimeException(
                sprintf('Unable to read %s.', $configurationPath)
            );
        }

        try {
            $configuration = json_decode(
                $contents,
                true,
                512,
                JSON_THROW_ON_ERROR
            );
        } catch (\JsonException $exception) {
            throw new \RuntimeException(
                sprintf(
                    'Invalid JSON in %s: %s',
                    $configurationPath,
                    $exception->getMessage()
                ),
                0,
                $exception
            );
        }

        if (!is_array($configuration)) {
            throw new \RuntimeException(
                sprintf('%s must contain a JSON object.', $configurationPath)
            );
        }

        if (!array_key_exists('githooks', $configuration)) {
            return false;
        }
        if (!is_array($configuration['githooks'])) {
            throw new \RuntimeException('githooks must be a JSON object.');
        }
        if (!array_key_exists('commit', $configuration['githooks'])) {
            return false;
        }
        if (!is_bool($configuration['githooks']['commit'])) {
            throw new \RuntimeException('githooks.commit must be a boolean.');
        }

        return $configuration['githooks']['commit'];
    }

    private function repositoryRoot(string $projectRoot): string
    {
        return $this->gitOutput(
            ['git', '-C', $projectRoot, 'rev-parse', '--show-toplevel'],
            $projectRoot,
            'Unable to locate the Git repository.'
        );
    }

    private function commonGitDirectory(string $repositoryRoot): string
    {
        return $this->gitOutput(
            [
                'git',
                '-C',
                $repositoryRoot,
                'rev-parse',
                '--path-format=absolute',
                '--git-common-dir',
            ],
            $repositoryRoot,
            'Unable to locate the common Git directory.'
        );
    }

    private function currentHooksPath(string $repositoryRoot): ?string
    {
        $result = $this->runner->run(
            ['git', '-C', $repositoryRoot, 'config', '--local', '--get', 'core.hooksPath'],
            $repositoryRoot,
            10
        );

        if ($result->exitCode === 1 && trim($result->stdout) === '') {
            return null;
        }
        $this->assertCommandSucceeded(
            $result,
            'Unable to read core.hooksPath.'
        );

        return trim($result->stdout);
    }

    private function setHooksPath(
        string $repositoryRoot,
        string $managedHooksPath
    ): void {
        $result = $this->runner->run(
            [
                'git',
                '-C',
                $repositoryRoot,
                'config',
                '--local',
                'core.hooksPath',
                $managedHooksPath,
            ],
            $repositoryRoot,
            10
        );
        $this->assertCommandSucceeded(
            $result,
            'Unable to set core.hooksPath.'
        );
    }

    private function restoreHooksPath(
        string $repositoryRoot,
        ?string $previousHooksPath
    ): void {
        if ($previousHooksPath !== null) {
            $result = $this->runner->run(
                [
                    'git',
                    '-C',
                    $repositoryRoot,
                    'config',
                    '--local',
                    'core.hooksPath',
                    $previousHooksPath,
                ],
                $repositoryRoot,
                10
            );
            $this->assertCommandSucceeded(
                $result,
                'Unable to restore core.hooksPath.'
            );
            return;
        }

        $result = $this->runner->run(
            [
                'git',
                '-C',
                $repositoryRoot,
                'config',
                '--local',
                '--unset-all',
                'core.hooksPath',
            ],
            $repositoryRoot,
            10
        );

        if (!in_array($result->exitCode, [0, 5], true)) {
            $this->assertCommandSucceeded(
                $result,
                'Unable to clear core.hooksPath.'
            );
        }
    }

    /**
     * @return array{
     *   version: int,
     *   previousHooksPath: ?string,
     *   projectRelativePath: string
     * }|null
     */
    private function readState(string $statePath): ?array
    {
        if (!is_file($statePath)) {
            return null;
        }

        $contents = file_get_contents($statePath);
        if ($contents === false) {
            throw new \RuntimeException(
                sprintf('Unable to read hook ownership state at %s.', $statePath)
            );
        }

        try {
            $state = json_decode($contents, true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException $exception) {
            throw new \RuntimeException(
                'The Blockstudio hook ownership state is invalid. No files were changed.',
                0,
                $exception
            );
        }

        if (
            !is_array($state)
            || !is_int($state['version'] ?? null)
            || !array_key_exists('previousHooksPath', $state)
            || (
                $state['previousHooksPath'] !== null
                && !is_string($state['previousHooksPath'])
            )
            || !is_string($state['projectRelativePath'] ?? null)
        ) {
            throw new \RuntimeException(
                'The Blockstudio hook ownership state is invalid. No files were changed.'
            );
        }

        return [
            'version' => $state['version'],
            'previousHooksPath' => $state['previousHooksPath'],
            'projectRelativePath' => $state['projectRelativePath'],
        ];
    }

    private function hookContents(
        string $projectRelativePath,
        ?string $previousHooksPath,
        string $repositoryRoot,
        string $commonGitDirectory,
        string $managedHookPath
    ): string {
        $resolvedPreviousHook = $this->resolveHooksDirectory(
            $previousHooksPath,
            $repositoryRoot,
            $commonGitDirectory
        ) . '/pre-commit';

        $previousHookExpression = $this->samePath(
            $resolvedPreviousHook,
            $managedHookPath
        )
            ? "''"
            : $this->previousHookExpression(
                $previousHooksPath,
                $commonGitDirectory
            );

        $projectStatement = $projectRelativePath === ''
            ? 'project_root="$repo_root"'
            : 'project_root="$repo_root"/'
                . $this->shellQuote($projectRelativePath);

        return sprintf(
            <<<'HOOK'
#!/bin/sh
%s
# Version: %d

set -u

repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || {
  echo "Blockstudio: unable to locate the Git repository." >&2
  exit 2
}

previous_hook=%s
if [ -n "$previous_hook" ] && [ -f "$previous_hook" ]; then
  if [ -x "$previous_hook" ]; then
    "$previous_hook" "$@" || exit $?
  else
    /bin/sh "$previous_hook" "$@" || exit $?
  fi
fi

%s
analysis="$project_root/vendor/bin/blockstudio-phpstan"

if [ ! -x "$analysis" ]; then
  echo "Blockstudio: vendor/bin/blockstudio-phpstan is missing or not executable. Run Composer install before committing." >&2
  exit 2
fi

cd "$project_root" || {
  echo "Blockstudio: unable to enter the configured project root." >&2
  exit 2
}

"$analysis" --root "$project_root" -- --no-progress
status=$?

if [ "$status" -ne 0 ]; then
  echo "Blockstudio: commit blocked by theme analysis." >&2
fi

exit "$status"

HOOK,
            self::MARKER,
            self::STATE_VERSION,
            $previousHookExpression,
            $projectStatement
        );
    }

    private function previousHookExpression(
        ?string $previousHooksPath,
        string $commonGitDirectory
    ): string {
        if ($previousHooksPath === null || $previousHooksPath === '') {
            return $this->shellQuote(
                $commonGitDirectory . '/hooks/pre-commit'
            );
        }
        if ($this->isAbsolutePath($previousHooksPath)) {
            return $this->shellQuote(
                $this->normalizePath($previousHooksPath) . '/pre-commit'
            );
        }

        return '"$repo_root"/'
            . $this->shellQuote(
                trim($this->normalizePath($previousHooksPath), '/')
                . '/pre-commit'
            );
    }

    private function resolveHooksDirectory(
        ?string $hooksPath,
        string $repositoryRoot,
        string $commonGitDirectory
    ): string {
        if ($hooksPath === null || $hooksPath === '') {
            return $commonGitDirectory . '/hooks';
        }
        if ($this->isAbsolutePath($hooksPath)) {
            return $this->normalizePath($hooksPath);
        }

        return $this->normalizePath($repositoryRoot . '/' . $hooksPath);
    }

    private function relativePath(string $base, string $path): string
    {
        $base = rtrim($this->normalizePath($base), '/');
        $path = rtrim($this->normalizePath($path), '/');

        if ($base === $path) {
            return '';
        }
        if (!str_starts_with($path, $base . '/')) {
            throw new \RuntimeException(
                'The Blockstudio project root must be inside its Git repository.'
            );
        }

        return substr($path, strlen($base) + 1);
    }

    private function existingDirectory(string $path): string
    {
        $realPath = realpath($path);
        if ($realPath === false || !is_dir($realPath)) {
            throw new \RuntimeException(
                sprintf('Project root does not exist: %s.', $path)
            );
        }

        return $this->normalizePath($realPath);
    }

    private function ensureDirectory(string $directory): void
    {
        if (
            !is_dir($directory)
            && !@mkdir($directory, 0775, true)
            && !is_dir($directory)
        ) {
            throw new \RuntimeException(
                sprintf('Unable to create %s.', $directory)
            );
        }
    }

    private function writeFile(
        string $path,
        string $contents,
        int $permissions
    ): void {
        $temporary = tempnam(dirname($path), '.blockstudio-');
        if ($temporary === false) {
            throw new \RuntimeException(
                sprintf('Unable to create a temporary file beside %s.', $path)
            );
        }

        try {
            if (file_put_contents($temporary, $contents) === false) {
                throw new \RuntimeException(
                    sprintf('Unable to write %s.', $path)
                );
            }
            if (!@chmod($temporary, $permissions)) {
                throw new \RuntimeException(
                    sprintf('Unable to set permissions on %s.', $path)
                );
            }
            if (!@rename($temporary, $path)) {
                throw new \RuntimeException(
                    sprintf('Unable to install %s.', $path)
                );
            }
        } finally {
            if (is_file($temporary)) {
                @unlink($temporary);
            }
        }
    }

    private function isOwnedFile(string $path): bool
    {
        $contents = file_get_contents($path);

        return is_string($contents)
            && str_contains($contents, self::MARKER);
    }

    private function removeDirectoryIfEmpty(string $directory): void
    {
        $entries = is_dir($directory) ? scandir($directory) : false;
        if ($entries === ['.', '..']) {
            @rmdir($directory);
        }
    }

    /**
     * @param non-empty-list<string> $command
     */
    private function gitOutput(
        array $command,
        string $workingDirectory,
        string $failureMessage
    ): string {
        $result = $this->runner->run($command, $workingDirectory, 10);
        $this->assertCommandSucceeded($result, $failureMessage);
        $output = trim($result->stdout);

        if ($output === '') {
            throw new \RuntimeException($failureMessage);
        }

        return $this->normalizePath($output);
    }

    private function assertCommandSucceeded(
        CommandResult $result,
        string $failureMessage
    ): void {
        if ($result->exitCode === 0 && !$result->timedOut) {
            return;
        }

        $detail = trim($result->stderr);
        throw new \RuntimeException(
            $failureMessage . ($detail !== '' ? ' ' . $detail : '')
        );
    }

    private function samePath(string $left, string $right): bool
    {
        return rtrim($this->normalizePath($left), '/')
            === rtrim($this->normalizePath($right), '/');
    }

    private function normalizePath(string $path): string
    {
        $path = str_replace('\\', '/', $path);
        $prefix = str_starts_with($path, '/') ? '/' : '';
        $parts = [];

        foreach (explode('/', $path) as $part) {
            if ($part === '' || $part === '.') {
                continue;
            }
            if ($part === '..' && $parts !== []) {
                array_pop($parts);
                continue;
            }
            $parts[] = $part;
        }

        return $prefix . implode('/', $parts);
    }

    private function isAbsolutePath(string $path): bool
    {
        return str_starts_with($path, '/')
            || preg_match('/^[A-Za-z]:[\\\\\/]/', $path) === 1;
    }

    private function shellQuote(string $value): string
    {
        return "'" . str_replace("'", "'\"'\"'", $value) . "'";
    }
}
