<?php

declare(strict_types=1);

namespace Blockstudio\PHPStan\Agents;

/**
 * Renders one project contract from discovered facts.
 *
 * Every section is emitted only when the project actually supports it, so a
 * theme that authors blocks and pages and a plugin that only consumes
 * Blockstudio produce different documents from the same generator.
 */
final class ContractDocument
{
    public const MARKER = '<!-- Generated by Blockstudio. Do not edit outside the notes section. -->';
    public const NOTES_START = '<!-- blockstudio:notes:start -->';
    public const NOTES_END = '<!-- blockstudio:notes:end -->';
    public const VERSION = 1;

    public function render(
        ProjectProfile $profile,
        PresetContract $contract,
        string $notes = ''
    ): string {
        $lines = [
            self::MARKER,
            sprintf('<!-- Version: %d -->', self::VERSION),
            '',
            sprintf('# Blockstudio contract for %s', $profile->name()),
            '',
            'Generated by `vendor/bin/blockstudio-agents` from `blockstudio.json` and'
            . ' the files in this project. It describes this project, not Blockstudio'
            . ' in general. Regenerate it after changing configuration or structure.',
        ];

        foreach (
            [
                'Project' => $this->project($profile),
                'What this project contains' => $this->contents($profile),
                'How work is authored' => $this->authoring($profile),
                'Enabled features' => $this->features($profile),
                'Correctness' => $this->correctness($contract),
                'Commands' => $this->commands($profile),
            ] as $heading => $body
        ) {
            if ($body === []) {
                continue;
            }

            $lines[] = '';
            $lines[] = '## ' . $heading;
            $lines[] = '';
            foreach ($body as $line) {
                $lines[] = $line;
            }
        }

        $lines[] = '';
        $lines[] = '## Project notes';
        $lines[] = '';
        $lines[] = 'Everything above is generated. Text between the markers below is'
            . ' preserved when this file is regenerated.';
        $lines[] = '';
        $lines[] = self::NOTES_START;
        if (trim($notes) !== '') {
            $lines[] = rtrim($notes);
        }
        $lines[] = self::NOTES_END;

        return implode("\n", $lines) . "\n";
    }

    /**
     * @return list<string>
     */
    private function project(ProjectProfile $profile): array
    {
        $lines = [
            sprintf('- Kind: %s `%s`.', $profile->kind(), $profile->name()),
            sprintf(
                '- Analysed root%s: %s.',
                count($profile->roots()) === 1 ? '' : 's',
                $this->inlineCode($profile->roots())
            ),
        ];

        $configuration = $profile->configurationPath();
        $lines[] = $configuration === null
            ? '- No `blockstudio.json` was found, so every setting is at its default.'
            : sprintf('- Configuration: `%s`.', $configuration);
        $lines[] = sprintf('- Analysis preset: `%s`.', $profile->preset());

        if ($profile->excludes() !== []) {
            $lines[] = sprintf(
                '- Excluded from discovery and analysis: %s.',
                $this->inlineCode($profile->excludes())
            );
        }

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function contents(ProjectProfile $profile): array
    {
        $lines = [];

        foreach ($profile->surfaces() as $surface) {
            $lines[] = sprintf(
                '- %s: %d in %s.',
                $surface->label,
                $surface->count,
                $this->inlineCode($surface->directories)
            );
        }

        if ($lines === []) {
            return [];
        }

        $namespaces = $profile->namespaces();
        if ($namespaces !== []) {
            $lines[] = sprintf(
                '- Block namespaces: %s.',
                $this->inlineCode($namespaces)
            );
        }

        $languages = $profile->templateLanguages();
        if ($languages !== []) {
            $lines[] = sprintf(
                '- Block templates are written in %s.',
                $this->sentenceList($languages)
            );
        }

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function authoring(ProjectProfile $profile): array
    {
        $lines = [];
        $surfaces = $this->surfaceDirectories($profile);

        if (isset($surfaces['Blocks'])) {
            $lines[] = '- A block is a directory holding a `block.json` and its'
                . ' template. Blockstudio discovers it from the filesystem, so no'
                . ' PHP file calls `register_block_type()`.';
            $lines[] = '- Field values reach the template as `$a[\'id\']`. A named'
                . ' group prefixes its children, anonymous groups and tabs stay in'
                . ' the parent scope, and a repeater is a list of rows.';

            if (!in_array('blockstudio', $surfaces['Blocks'], true)) {
                $lines[] = sprintf(
                    '- Blocks live in %s rather than the default `blockstudio`'
                    . ' folder, so discovery is pointed there through the'
                    . ' `blockstudio/path` filter or `Blockstudio\\Build::init()`.',
                    $this->inlineCode($surfaces['Blocks'])
                );
            }
        }

        if ($profile->kind() === 'WordPress plugin') {
            $lines[] = '- This is a plugin, so nothing is discovered from the'
                . ' active theme. Every source directory this plugin owns has to be'
                . ' registered explicitly, and template paths must never assume a'
                . ' theme location.';
        }

        if (isset($surfaces['Pages'])) {
            $lines[] = sprintf(
                '- A page is a `page.json` beside a template in %s. Page sources are'
                . ' ordinary HTML, PHP, Twig, Blade, or Markdown; serialized'
                . ' `wp:` block comments do not belong in them.',
                $this->inlineCode($surfaces['Pages'])
            );
        }
        if (isset($surfaces['Page collections'])) {
            $lines[] = '- A `pages.json` manifest turns a directory into a page'
                . ' collection with its own URL base and, optionally, its own post'
                . ' type.';
        }
        if (isset($surfaces['Patterns'])) {
            $lines[] = '- A pattern is a `pattern.json` beside a template. Patterns'
                . ' are registered in memory and create no database entries.';
        }
        if (isset($surfaces['Reusable fields'])) {
            $lines[] = '- A `field.json` defines fields once and is referenced from'
                . ' blocks as `custom/<name>`, with `idStructure` and `overrides`'
                . ' applied per instance.';
        }
        if (isset($surfaces['Block extensions'])) {
            $lines[] = '- Extension JSON in an `extensions` directory adds fields to'
                . ' blocks this project does not own.';
        }
        if (
            isset($surfaces['Site Editor templates'])
            || isset($surfaces['Site Editor template parts'])
        ) {
            $lines[] = '- Site Editor templates and parts are file backed through'
                . ' `template.json` and `part.json`, and stay editable in WordPress.';
        }
        if (
            isset($surfaces['Database schemas'])
            || isset($surfaces['RPC endpoints'])
            || isset($surfaces['Cron definitions'])
        ) {
            $lines[] = '- A block owns its backend through the files beside it:'
                . ' `db.php` for storage, `rpc.php` for endpoints, and `cron.php`'
                . ' for scheduled work.';
        }

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function features(ProjectProfile $profile): array
    {
        $lines = [];

        foreach ($profile->features() as $feature) {
            $lines[] = sprintf('- **%s**', $feature->label);
            foreach ($feature->details as $detail) {
                $lines[] = '  - ' . $detail;
            }
        }

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function correctness(PresetContract $contract): array
    {
        $lines = [
            sprintf(
                'Analysis runs the `%s` preset. What follows is what that preset'
                . ' registers, so it changes when the preset does.',
                $contract->preset()
            ),
        ];

        $strictness = $contract->strictness();
        if ($strictness !== []) {
            $lines[] = '';
            foreach ($strictness as $line) {
                $lines[] = '- ' . $line;
            }
        }

        $first = true;
        foreach ($contract->layers() as $layer) {
            $lines[] = '';
            $lines[] = sprintf(
                'The `%s` layer %s:',
                $layer['label'],
                $first ? 'enforces' : 'adds'
            );
            $lines[] = '';
            foreach ($layer['contracts'] as $line) {
                $lines[] = '- ' . $line;
            }
            $first = false;
        }

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function commands(ProjectProfile $profile): array
    {
        $lines = [];

        foreach ($profile->commands() as $command) {
            $lines[] = sprintf('- `%s`: %s', $command->command, $command->purpose);
        }

        return $lines;
    }

    /**
     * @return array<string, list<string>>
     */
    private function surfaceDirectories(ProjectProfile $profile): array
    {
        $directories = [];

        foreach ($profile->surfaces() as $surface) {
            $directories[$surface->label] = $surface->directories;
        }

        return $directories;
    }

    /**
     * @param list<string> $values
     */
    private function inlineCode(array $values): string
    {
        return implode(
            ', ',
            array_map(static fn(string $value): string => '`' . $value . '`', $values)
        );
    }

    /**
     * @param list<string> $values
     */
    private function sentenceList(array $values): string
    {
        if (count($values) < 2) {
            return implode('', $values);
        }

        $last = array_pop($values);

        return implode(', ', $values) . ' and ' . $last;
    }
}
