<?php

declare(strict_types=1);

namespace Blockstudio\PHPStan\Tests\Unit\GitHooks;

use Blockstudio\PHPStan\GitHooks\HookManager;
use Blockstudio\PHPStan\Theme\CommandResult;
use Blockstudio\PHPStan\Theme\CommandRunner;
use PHPUnit\Framework\TestCase;

final class HookManagerTest extends TestCase
{
    /**
     * @var list<string>
     */
    private array $temporaryDirectories = [];

    protected function tearDown(): void
    {
        foreach (array_reverse($this->temporaryDirectories) as $directory) {
            $this->removeDirectory($directory);
        }
        $this->temporaryDirectories = [];
    }

    public function testFreshEnableAndRepeatedRefreshAreIdempotent(): void
    {
        $repository = $this->repository('fresh repository');
        $this->configuration($repository, true);
        $manager = new HookManager();

        $first = $manager->sync(
            $repository,
            $repository . '/blockstudio.json'
        );

        self::assertSame('enabled', $first->status);
        self::assertFileExists($first->hookPath);
        self::assertTrue(is_executable($first->hookPath));
        $hookContents = (string) file_get_contents($first->hookPath);
        self::assertStringContainsString(
            '# Generated by Blockstudio. Do not edit.',
            $hookContents
        );
        self::assertStringNotContainsString('prettier', $hookContents);
        self::assertStringNotContainsString('blockstudio-fmt', $hookContents);
        self::assertStringNotContainsString(
            'div' . 'ine',
            strtolower($hookContents)
        );
        self::assertStringNotContainsString(
            '/vendor/bin/' . 'd' . 'v ',
            strtolower($hookContents)
        );
        self::assertSame(
            dirname($first->hookPath),
            $this->gitOutput(
                $repository,
                ['git', 'config', '--local', '--get', 'core.hooksPath']
            )
        );

        file_put_contents(
            $first->hookPath,
            "#!/bin/sh\n# Generated by Blockstudio. Do not edit.\n# drift\n"
        );
        chmod($first->hookPath, 0755);
        $statePath = dirname(dirname($first->hookPath))
            . '/hooks-state.json';
        $state = json_decode(
            (string) file_get_contents($statePath),
            true,
            512,
            JSON_THROW_ON_ERROR
        );
        self::assertIsArray($state);
        $state['version'] = 0;
        file_put_contents(
            $statePath,
            json_encode(
                $state,
                JSON_PRETTY_PRINT
                    | JSON_UNESCAPED_SLASHES
                    | JSON_THROW_ON_ERROR
            ) . "\n"
        );

        $second = $manager->sync(
            $repository,
            $repository . '/blockstudio.json'
        );
        $contents = (string) file_get_contents($second->hookPath);

        self::assertSame($first->hookPath, $second->hookPath);
        self::assertStringNotContainsString('# drift', $contents);
        self::assertStringContainsString('# Version: 1', $contents);
        self::assertTrue(is_executable($second->hookPath));
        self::assertStringContainsString(
            '"version": 1',
            (string) file_get_contents($statePath)
        );

        $manager->remove($repository);
        $configured = $this->command(
            ['git', 'config', '--local', '--get', 'core.hooksPath'],
            $repository
        );
        self::assertSame(1, $configured->exitCode);
    }

    public function testDisableRestoresPriorHooksPathAndPreservesUserHook(): void
    {
        $repository = $this->repository('prior hook repository');
        $customHooks = $repository . '/.custom-hooks';
        mkdir($customHooks, 0775, true);
        $userHook = $customHooks . '/pre-commit';
        file_put_contents($userHook, "#!/bin/sh\nexit 0\n");
        chmod($userHook, 0755);
        $this->git(
            $repository,
            ['git', 'config', '--local', 'core.hooksPath', '.custom-hooks']
        );
        $this->configuration($repository, true);
        $manager = new HookManager();
        $enabled = $manager->sync(
            $repository,
            $repository . '/blockstudio.json'
        );

        $this->configuration($repository, false);
        $disabled = $manager->sync(
            $repository,
            $repository . '/blockstudio.json'
        );

        self::assertSame('disabled', $disabled->status);
        self::assertFileDoesNotExist($enabled->hookPath);
        self::assertFileExists($userHook);
        self::assertSame(
            '.custom-hooks',
            $this->gitOutput(
                $repository,
                ['git', 'config', '--local', '--get', 'core.hooksPath']
            )
        );
    }

    public function testDisablePreservesAUserHooksPathChangedAfterEnable(): void
    {
        $repository = $this->repository('changed hook repository');
        $this->configuration($repository, true);
        $manager = new HookManager();
        $enabled = $manager->sync(
            $repository,
            $repository . '/blockstudio.json'
        );
        $this->git(
            $repository,
            ['git', 'config', '--local', 'core.hooksPath', '.new-hooks']
        );

        $manager->remove($repository);

        self::assertSame(
            '.new-hooks',
            $this->gitOutput(
                $repository,
                ['git', 'config', '--local', '--get', 'core.hooksPath']
            )
        );
        self::assertFileDoesNotExist($enabled->hookPath);
    }

    public function testEnableRefusesAUserOwnedFileAtTheManagedPath(): void
    {
        $repository = $this->repository('user managed path');
        $commonGitDirectory = $this->gitOutput(
            $repository,
            [
                'git',
                'rev-parse',
                '--path-format=absolute',
                '--git-common-dir',
            ]
        );
        $managedDirectory = $commonGitDirectory . '/blockstudio/hooks';
        mkdir($managedDirectory, 0775, true);
        $userHook = $managedDirectory . '/pre-commit';
        file_put_contents($userHook, "#!/bin/sh\necho user\n");
        chmod($userHook, 0755);
        $this->configuration($repository, true);

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('Refusing to overwrite the user-owned hook');

        (new HookManager())->sync(
            $repository,
            $repository . '/blockstudio.json'
        );
    }

    public function testMissingDependenciesAndAnalysisFailuresBlockCommits(): void
    {
        $repository = $this->repository('commit gate repository');
        $this->configuration($repository, true);
        $manager = new HookManager();
        $manager->sync($repository, $repository . '/blockstudio.json');

        file_put_contents($repository . '/missing.txt', "missing\n");
        $this->git($repository, ['git', 'add', 'missing.txt']);
        $missing = $this->command(
            ['git', 'commit', '-m', 'missing dependency'],
            $repository
        );

        self::assertNotSame(0, $missing->exitCode);
        self::assertStringContainsString(
            'vendor/bin/blockstudio-phpstan is missing',
            $missing->stderr
        );

        $this->analysisStub($repository);
        file_put_contents($repository . '/.analysis-fail', "1\n");
        $failed = $this->command(
            ['git', 'commit', '-m', 'analysis failure'],
            $repository
        );

        self::assertSame(1, $failed->exitCode);
        self::assertStringContainsString(
            'commit blocked by theme analysis',
            $failed->stderr
        );

        unlink($repository . '/.analysis-fail');
        $passed = $this->command(
            ['git', 'commit', '-m', 'analysis success'],
            $repository
        );

        self::assertSame(0, $passed->exitCode, $passed->stderr);
        self::assertSame(
            "-- --no-progress\n",
            file_get_contents($repository . '/.analysis-arguments')
        );
        self::assertSame(
            realpath($repository) . "\n",
            file_get_contents($repository . '/.analysis-working-directory')
        );
    }

    public function testManagedHookRunsRealExtremeAnalysis(): void
    {
        $repository = $this->repository('real analysis repository');
        $this->configuration($repository, true, 'extreme-theme');
        $directory = $repository . '/vendor/bin';
        mkdir($directory, 0775, true);
        $canonical = dirname(__DIR__, 3) . '/bin/blockstudio-phpstan';
        $wrapper = $directory . '/blockstudio-phpstan';
        file_put_contents(
            $wrapper,
            "#!/bin/sh\nexec "
                . escapeshellarg(PHP_BINARY)
                . ' '
                . escapeshellarg($canonical)
                . " \"\$@\"\n"
        );
        chmod($wrapper, 0755);
        file_put_contents(
            $repository . '/theme.php',
            "<?php\n\neval('return true;');\n"
        );
        file_put_contents(
            $repository . '/style.css',
            "/*\nTheme Name: Hook Fixture\n*/\n"
        );
        $this->git(
            $repository,
            ['git', 'add', 'blockstudio.json', 'style.css', 'theme.php']
        );
        (new HookManager())->sync(
            $repository,
            $repository . '/blockstudio.json'
        );

        $failed = $this->command(
            ['git', 'commit', '-m', 'unsafe theme'],
            $repository
        );

        self::assertSame(1, $failed->exitCode);
        self::assertStringContainsString(
            'eval()',
            $failed->stdout . $failed->stderr
        );

        file_put_contents(
            $repository . '/theme.php',
            "<?php\n\ndeclare(strict_types=1);\n\n"
                . "function clean_fixture(): string\n{\n"
                . "    return 'ok';\n}\n"
        );
        $this->git($repository, ['git', 'add', 'theme.php']);
        $passed = $this->command(
            ['git', 'commit', '-m', 'clean theme'],
            $repository
        );

        self::assertSame(0, $passed->exitCode, $passed->stderr);
    }

    public function testExistingHookChainsBeforeAnalysis(): void
    {
        $repository = $this->repository('hook chaining repository');
        $customHooks = $repository . '/hooks before blockstudio';
        mkdir($customHooks, 0775, true);
        $userHook = $customHooks . '/pre-commit';
        file_put_contents(
            $userHook,
            "#!/bin/sh\nprintf 'previous\\n' >> .previous-hook-ran\n"
        );
        chmod($userHook, 0755);
        $this->git(
            $repository,
            [
                'git',
                'config',
                '--local',
                'core.hooksPath',
                'hooks before blockstudio',
            ]
        );
        $this->configuration($repository, true);
        $this->analysisStub($repository);
        (new HookManager())->sync(
            $repository,
            $repository . '/blockstudio.json'
        );

        file_put_contents($repository . '/chain.txt', "chain\n");
        $this->git($repository, ['git', 'add', 'chain.txt']);
        $commit = $this->command(
            ['git', 'commit', '-m', 'chain hooks'],
            $repository
        );

        self::assertSame(0, $commit->exitCode, $commit->stderr);
        self::assertSame(
            "previous\n",
            file_get_contents($repository . '/.previous-hook-ran')
        );
    }

    public function testLinkedCheckoutResolvesItsOwnNestedProjectWithSpaces(): void
    {
        $root = $this->temporaryDirectory('linked checkouts');
        $repository = $root . '/main repository';
        mkdir($repository, 0775, true);
        $this->initializeRepository($repository);
        $project = $repository . '/nested theme';
        mkdir($project, 0775, true);
        $this->configuration($project, true);
        $this->analysisStub($project);
        $customHooks = $repository . '/.custom-hooks';
        mkdir($customHooks, 0775, true);
        file_put_contents(
            $customHooks . '/pre-commit',
            "#!/bin/sh\nprintf 'linked\\n' > .linked-prior-hook\n"
        );
        chmod($customHooks . '/pre-commit', 0755);
        file_put_contents($repository . '/tracked.txt', "base\n");
        $this->git($repository, ['git', 'add', '.']);
        $this->git($repository, ['git', 'commit', '-m', 'base']);
        $this->git(
            $repository,
            ['git', 'config', '--local', 'core.hooksPath', '.custom-hooks']
        );

        $linked = $root . '/linked repository';
        $this->git(
            $repository,
            ['git', 'work' . 'tree', 'add', '-b', 'linked-test', $linked]
        );
        $linkedProject = $linked . '/nested theme';
        (new HookManager())->sync(
            $linkedProject,
            $linkedProject . '/blockstudio.json'
        );

        file_put_contents($linked . '/linked.txt', "linked\n");
        $this->git($linked, ['git', 'add', 'linked.txt']);
        $commit = $this->command(
            ['git', 'commit', '-m', 'linked commit'],
            $linked
        );

        self::assertSame(0, $commit->exitCode, $commit->stderr);
        self::assertSame(
            "-- --no-progress\n",
            file_get_contents($linkedProject . '/.analysis-arguments')
        );
        self::assertSame(
            realpath($linkedProject) . "\n",
            file_get_contents(
                $linkedProject . '/.analysis-working-directory'
            )
        );
        self::assertSame(
            "linked\n",
            file_get_contents($linked . '/.linked-prior-hook')
        );
        self::assertFileDoesNotExist($repository . '/.linked-prior-hook');
    }

    public function testInvalidConfigurationNeverChangesGitSettings(): void
    {
        $repository = $this->repository('invalid config repository');
        file_put_contents(
            $repository . '/blockstudio.json',
            '{"githooks":{"commit":"yes"}}'
        );

        try {
            (new HookManager())->sync(
                $repository,
                $repository . '/blockstudio.json'
            );
            self::fail('Expected invalid configuration to fail.');
        } catch (\RuntimeException $exception) {
            self::assertStringContainsString(
                'githooks.commit must be a boolean',
                $exception->getMessage()
            );
        }

        $result = $this->command(
            ['git', 'config', '--local', '--get', 'core.hooksPath'],
            $repository
        );
        self::assertSame(1, $result->exitCode);
    }

    private function repository(string $name): string
    {
        $root = $this->temporaryDirectory($name);
        $repository = $root . '/repository';
        mkdir($repository, 0775, true);
        $this->initializeRepository($repository);

        return $repository;
    }

    private function initializeRepository(string $repository): void
    {
        $this->git($repository, ['git', 'init', '--quiet']);
        $this->git(
            $repository,
            ['git', 'config', 'user.email', 'tests@blockstudio.dev']
        );
        $this->git(
            $repository,
            ['git', 'config', 'user.name', 'Blockstudio Tests']
        );
        $this->git($repository, ['git', 'config', 'commit.gpgsign', 'false']);
    }

    private function configuration(
        string $project,
        bool $enabled,
        ?string $preset = null
    ): void {
        $configuration = ['githooks' => ['commit' => $enabled]];
        if ($preset !== null) {
            $configuration['phpstan'] = ['preset' => $preset];
        }

        file_put_contents(
            $project . '/blockstudio.json',
            json_encode(
                $configuration,
                JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR
            ) . "\n"
        );
    }

    private function analysisStub(string $project): void
    {
        $directory = $project . '/vendor/bin';
        if (!is_dir($directory)) {
            mkdir($directory, 0775, true);
        }

        $path = $directory . '/blockstudio-phpstan';
        file_put_contents(
            $path,
            <<<'SH'
#!/bin/sh
printf '%s\n' "$*" > .analysis-arguments
pwd > .analysis-working-directory
if [ -f .analysis-fail ]; then
  echo "Fixture analysis failed." >&2
  exit 1
fi
exit 0
SH
            . "\n"
        );
        chmod($path, 0755);
    }

    /**
     * @param list<string> $arguments
     */
    private function git(string $repository, array $arguments): void
    {
        $result = $this->command($arguments, $repository);

        self::assertSame(
            0,
            $result->exitCode,
            trim($result->stderr . "\n" . $result->stdout)
        );
    }

    /**
     * @param list<string> $arguments
     */
    private function gitOutput(string $repository, array $arguments): string
    {
        $result = $this->command($arguments, $repository);
        self::assertSame(0, $result->exitCode, $result->stderr);

        return trim($result->stdout);
    }

    /**
     * @param non-empty-list<string> $arguments
     */
    private function command(
        array $arguments,
        string $workingDirectory
    ): CommandResult {
        return (new CommandRunner())->run(
            $arguments,
            $workingDirectory,
            20
        );
    }

    private function temporaryDirectory(string $name): string
    {
        $directory = sys_get_temp_dir()
            . '/blockstudio-'
            . preg_replace('/[^a-z]+/i', '-', $name)
            . '-'
            . bin2hex(random_bytes(5));
        mkdir($directory, 0775, true);
        $this->temporaryDirectories[] = $directory;

        return $directory;
    }

    private function removeDirectory(string $directory): void
    {
        if (!is_dir($directory)) {
            return;
        }

        $items = scandir($directory);
        if ($items === false) {
            return;
        }

        foreach ($items as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }

            $path = $directory . '/' . $item;
            if (is_dir($path) && !is_link($path)) {
                $this->removeDirectory($path);
            } else {
                @unlink($path);
            }
        }

        @rmdir($directory);
    }
}
